version: "3"
services:
  bicc_xwiki_db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: bicc_xwiki
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: docker2020
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  bicc_xwiki:
    image: requarks/wiki:2
    depends_on:
      - bicc_xwiki_db
    environment:
      DB_TYPE: postgres
      DB_HOST: bicc_xwiki_db
      DB_PORT: 5432
      DB_USER: dockeruser
      DB_PASS: docker2020
      DB_NAME: bicc_xwiki
    restart: unless-stopped
    ports:
      - "50080:3000"

volumes:
  db-data: